# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 600)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Form.setStyleSheet("QWidget {\n"
"    background-color: rgb(58, 58, 58);\n"
"}\n"
"QScrollArea {\n"
"    border: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"    width: 10px;\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"    margin: 0 0 0 0;\n"
"}\n"
"QScrollBar::sub-line:vertical, QScrollBar::add-line:vertical, QScrollBar::sub-page:vertical, QScrollBar::add-page:vetical {\n"
"    background: none;\n"
"    border: none\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(110, 133, 211);\n"
"    border: none;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(125, 151, 239);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background-color: rgb(88, 106, 234);\n"
"    background-color: rgb(81, 110, 203);\n"
"}\n"
"\n"
"\n"
"QScrollBar:horizontal {\n"
"    height: 10px;\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"    margin: 0 0 0 0;\n"
"}\n"
"QScrollBar::sub-line:horizontal, QScrollBar::add-line:horizontal, QScrollBar::sub-page:horizontal, QScrollBar::add-page:vetical {\n"
"    background: none;\n"
"    border: none\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(110, 133, 211);\n"
"    border: none;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgb(125, 151, 239);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {\n"
"    background-color: rgb(88, 106, 234);\n"
"    background-color: rgb(81, 110, 203);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 478, 578))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.container_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.container_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.container_widget.setStyleSheet("QWidget {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 116, 228);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(40, 138, 232);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(61, 149, 234);\n"
"}")
        self.container_widget.setObjectName("container_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.container_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.classic_group_box = QtWidgets.QGroupBox(self.container_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.classic_group_box.setFont(font)
        self.classic_group_box.setObjectName("classic_group_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.classic_group_box)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.classic_group_box)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.classic_group_box)
        self.modern_group_box = QtWidgets.QGroupBox(self.container_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.modern_group_box.setFont(font)
        self.modern_group_box.setObjectName("modern_group_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.modern_group_box)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.modern_group_box)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.modern_group_box)
        self.verticalLayout_2.addWidget(self.container_widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SwitchControl"))
        self.classic_group_box.setTitle(_translate("Form", "Classic"))
        self.label.setText(_translate("Form", "SwitchControl with Classic style"))
        self.modern_group_box.setTitle(_translate("Form", "Modern"))
        self.label_2.setText(_translate("Form", "SwitchControl with Modern style"))
